//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int IdAdmin { get; set; }
        public string NomAdmin { get; set; }
        public string PrenomAdmin { get; set; }
        public string LoginAdmin { get; set; }
        public string PasswordAdmin { get; set; }
    }
}
