//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epreuve
    {
        public Epreuve()
        {
            this.Note = new HashSet<Note>();
        }
    
        public int IdEpreuve { get; set; }
        public int IdModule { get; set; }
        public int idMatiere { get; set; }
        public Nullable<double> CoefEpreuve { get; set; }
        public Nullable<double> Rang { get; set; }
        public string Type { get; set; }
        public Nullable<byte> File { get; set; }
    
        public virtual Matiere Matiere { get; set; }
        public virtual ICollection<Note> Note { get; set; }
    }
}
