//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.etudier = new HashSet<etudier>();
            this.Matiere = new HashSet<Matiere>();
        }
    
        public int IdModule { get; set; }
        public int IdNiveau { get; set; }
        public string Matricule { get; set; }
        public string NomModule { get; set; }
        public Nullable<int> NbreHeures { get; set; }
        public Nullable<int> moyenneV { get; set; }
    
        public virtual Enseignant Enseignant { get; set; }
        public virtual ICollection<etudier> etudier { get; set; }
        public virtual ICollection<Matiere> Matiere { get; set; }
        public virtual Niveau Niveau { get; set; }
    }
}
