//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Niveau
    {
        public Niveau()
        {
            this.inscription = new HashSet<inscription>();
            this.Module = new HashSet<Module>();
        }
    
        public int IdNiveau { get; set; }
        public string Libelle { get; set; }
    
        public virtual ICollection<inscription> inscription { get; set; }
        public virtual ICollection<Module> Module { get; set; }
    }
}
